### ISSUE TITLE
Upgrade React to v16 (Fiber)

### ISSUE THREAD

**Issue by tferreira** [tferreira/piggydime#62]
React 16 is now available for public use in BETA.
We should install it to make sure the app works with it.

Install instructions:
```sh
# Yarn
yarn add react@next react-dom@next
```

Before installing, we need to fix deprecation warnings:

```sh
modulesaddDependencyTo is deprecated in favor of
result.messages.dependency; postcss-loader >= v1.0.0 will
automatically add your imported files to webpack's file watcher.
For more information, see
https://github.com/postcss/postcss-import          #dependency-message-support
```

**Comment by tferreira** [comment]
There is some issues with the `react-tap-event-plugin` lib that is used by `material-ui`.

```sh
ERROR in ./~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Cannot resolve module 'react-dom/lib/EventPluginHub' in /Users/thomas/piggydime/static/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-41

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react-dom/lib/EventConstants' in /Users/thomas/piggydime/static/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 22:21-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react-dom/lib/EventPluginUtils' in /Users/thomas/piggydime/static/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 23:23-64

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react-dom/lib/EventPropagators' in /Users/thomas/piggydime/static/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 24:23-64

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react-dom/lib/SyntheticUIEvent' in /Users/thomas/piggydime/static/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 25:23-64

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react-dom/lib/ViewportMetrics' in /Users/thomas/piggydime/static/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-62
```

Currently waiting for a fix. Issue description updated with a link to the issue on the `material-ui` repository.

**Comment by lostpebble** [comment]
Issue fixed with this pull request https://github.com/callemall/material-ui/pull/7624.

Currently working fine with my project and React Fiber beta 2.

**Comment by tferreira** [comment]
No problem, it's good to have feedback anyways :)

**Comment by tferreira** [comment]
The `next` version of material-ui works with React 16, but some components are still missing (like SelectField).

Also, `injectTapEventPlugin()` does not work anymore. Putting this issue on standby.
